### ISSUE TITLE
Unraid - The requested URL was not found on the server

### ISSUE THREAD

**Issue by danchappers** [riffsphereha/newznabarr#1]
Hi,

I've just installed this on Unraid but when I try to access it I get the error: The requested URL was not found on the server

I'm sure this is a me issue, but I can't figure out why. I've tried changing the port but have the same issue.

**Comment by Healzangels** [comment]
Seeing the same thing while trying to access the WebGui on Unraid

`The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

Thanks!

**Comment by jeffphilly** [comment]
Same here. I am trying to figure it out but cant get it. Same issue when i tried to use the compose file.

**Comment by stayupthetree** [comment]
You all need to hitup grtgbln on the Unraid forums, they did the template wrong, probably they left the r off of riffsphereha

**Comment by riffsphereha** [comment]
I guess everyone is trying to load the webui, since the grtgbl unraid template seems to work (though he has puid and pgid at 1000, not 99 and 100 respectively as suggested for unraid).

Well, there is no webui, maybe I need to add one to confirm it's working.

**Comment by riffsphereha** [comment]
Pretty sure this issue was related to not having a webui.

Just made an update with something that's better than no webui, showing images on how to configure :-)
Let me know if that fixes it or the issue remains.

**Comment by stayupthetree** [comment]
> Pretty sure this issue was related to not having a webui.
> 
> Just made an update with something that's better than no webui, showing images on how to configure :-) Let me know if that fixes it or the issue remains.

Ahh my bad.  I just noticed anytime I click any of his link for he took me to https://github.com/iffsphereha/newznabarr, for some reason he left off the r at the beginning of your user name

**Comment by jeffphilly** [comment]
Can confirm, this is a big help with the images!
